app:
  description: Welcome to ${app.name}
  name: My app
db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200

dbValues: '{connectionString: ''http://__'', userName: ''Karl'', password: ''pass''}'
management:
  endpoints:
    web:
      exposure:
        include: '*'
my:
  greeting: Hey Suckas!
  list:
    values: One, Two, Three

spring:
  profiles:
    active:
    - test